#!/usr/bin/env bash
# 一次性脚手架脚本：为 nav 中登记的所有「内容页」生成占位 stub。
# 总览页 (index.md) 不在此处生成，由人工撰写完整内容。
set -e
DOCS="$(dirname "$0")/../docs"

make_stub () {
  local path="$1"; shift
  local title="$1"; shift
  local full="$DOCS/$path"
  # 已存在则跳过，避免覆盖已写好的完整内容
  if [ -f "$full" ]; then echo "skip  $path"; return; fi
  mkdir -p "$(dirname "$full")"
  printf '# %s\n\n!!! note "编写中"\n    本页完整教程正在编写中，敬请期待。\n' "$title" > "$full"
  echo "write $path"
}

# ===== AP CSA Unit 1 =====
make_stub AP_CSA/unit1/software_engineering.md "程序与软件工程导论"
make_stub AP_CSA/unit1/variables_types.md "变量与基本数据类型"
make_stub AP_CSA/unit1/expressions_assignment.md "表达式与赋值"
make_stub AP_CSA/unit1/compound_casting.md "复合赋值与类型转换"
make_stub AP_CSA/unit1/objects_classes.md "对象与类的概念"
make_stub AP_CSA/unit1/method_calls.md "方法调用"
make_stub AP_CSA/unit1/return_values.md "带返回值的方法"
make_stub AP_CSA/unit1/strings.md "字符串对象与方法"
make_stub AP_CSA/unit1/wrapper_classes.md "包装类"
make_stub AP_CSA/unit1/math_class.md "Math 类"
# ===== AP CSA Unit 2 =====
make_stub AP_CSA/unit2/boolean_expressions.md "布尔表达式与关系运算"
make_stub AP_CSA/unit2/if_statements.md "if 与 if-else 语句"
make_stub AP_CSA/unit2/logical_operators.md "逻辑运算符与德摩根定律"
make_stub AP_CSA/unit2/nested_conditionals.md "嵌套条件与多分支"
make_stub AP_CSA/unit2/while_loops.md "while 循环"
make_stub AP_CSA/unit2/for_loops.md "for 循环"
make_stub AP_CSA/unit2/nested_loops.md "嵌套循环"
make_stub AP_CSA/unit2/informal_runtime.md "算法与非正式运行时分析"
# ===== AP CSA Unit 3 =====
make_stub AP_CSA/unit3/class_anatomy.md "类的结构"
make_stub AP_CSA/unit3/constructors.md "构造方法与 new 运算符"
make_stub AP_CSA/unit3/accessor_mutator.md "访问器与修改器方法"
make_stub AP_CSA/unit3/this_parameters.md "this 关键字与参数传递"
make_stub AP_CSA/unit3/static_members.md "静态变量与静态方法"
make_stub AP_CSA/unit3/scope_access.md "作用域与访问控制"
make_stub AP_CSA/unit3/encapsulation_javadoc.md "封装与 javadoc 设计"
# ===== AP CSA Unit 4 =====
make_stub AP_CSA/unit4/arrays.md "一维数组"
make_stub AP_CSA/unit4/array_traversal.md "数组遍历与 for-each"
make_stub AP_CSA/unit4/array_algorithms.md "数组标准算法"
make_stub AP_CSA/unit4/arraylist.md "ArrayList"
make_stub AP_CSA/unit4/arraylist_algorithms.md "ArrayList 标准算法"
make_stub AP_CSA/unit4/array_2d.md "二维数组"
make_stub AP_CSA/unit4/array_2d_traversal.md "二维数组遍历"
make_stub AP_CSA/unit4/text_files_scanner.md "文本文件与 Scanner"
make_stub AP_CSA/unit4/searching.md "顺序查找与二分查找"
make_stub AP_CSA/unit4/sorting.md "排序算法"
make_stub AP_CSA/unit4/recursion.md "递归"
# ===== Bronze =====
make_stub Bronze/time_complexity.md "时间复杂度"
make_stub Bronze/intro_data_structures.md "数据结构入门"
make_stub Bronze/simulation.md "模拟"
make_stub Bronze/complete_search_basic.md "基础完全搜索"
make_stub Bronze/complete_search_recursion.md "递归完全搜索"
make_stub Bronze/intro_sorting.md "排序入门"
make_stub Bronze/sets_maps.md "集合与映射"
make_stub Bronze/casework.md "分类讨论"
make_stub Bronze/intro_greedy.md "贪心入门"
make_stub Bronze/intro_graphs.md "图论入门"
make_stub Bronze/rectangle_geometry.md "矩形几何"
make_stub Bronze/ad_hoc.md "Ad Hoc 杂题"
# ===== Silver =====
make_stub Silver/prefix_sums.md "前缀和入门"
make_stub Silver/prefix_sums_advanced.md "前缀和进阶"
make_stub Silver/two_pointers.md "双指针"
make_stub Silver/binary_search_sorted.md "有序数组二分"
make_stub Silver/binary_search.md "二分答案"
make_stub Silver/custom_comparators.md "自定义比较器与坐标压缩"
make_stub Silver/greedy_sorting.md "排序贪心"
make_stub Silver/priority_queues.md "优先队列"
make_stub Silver/graph_traversal.md "图的遍历"
make_stub Silver/flood_fill.md "洪水填充"
make_stub Silver/intro_trees.md "树算法入门"
make_stub Silver/functional_graphs.md "函数图"
make_stub Silver/bitwise.md "位运算入门"
# ===== Gold =====
make_stub Gold/divisibility.md "整除"
make_stub Gold/modular_arithmetic.md "模运算"
make_stub Gold/combinatorics.md "组合数学"
make_stub Gold/intro_dp.md "DP 入门"
make_stub Gold/knapsack.md "背包"
make_stub Gold/grid_paths.md "网格路径"
make_stub Gold/lis.md "最长上升子序列"
make_stub Gold/bitmask_dp.md "状压 DP"
make_stub Gold/range_dp.md "区间 DP"
make_stub Gold/digit_dp.md "数位 DP"
make_stub Gold/unweighted_shortest_path.md "无权最短路"
make_stub Gold/dsu.md "并查集"
make_stub Gold/topological_sort.md "拓扑排序"
make_stub Gold/dijkstra.md "非负权最短路"
make_stub Gold/mst.md "最小生成树"
make_stub Gold/sorted_sets.md "有序集合进阶"
make_stub Gold/stacks.md "栈"
make_stub Gold/sliding_window.md "滑动窗口"
make_stub Gold/point_update_range_sum.md "单点修改区间和"
make_stub Gold/euler_tour.md "欧拉序"
make_stub Gold/dp_on_trees.md "树形 DP 入门"
make_stub Gold/all_roots_dp.md "换根 DP"
make_stub Gold/hashing.md "哈希"
make_stub Gold/meet_in_middle.md "折半搜索"
make_stub Gold/ternary_search.md "单峰函数三分"
# ===== Platinum =====
make_stub Platinum/segtree_applications.md "线段树进阶应用"
make_stub Platinum/sweep_line_range.md "扫描线区间查询"
make_stub Platinum/range_update_range_query.md "区间修改区间查询"
make_stub Platinum/sparse_segtree.md "动态开点线段树"
make_stub Platinum/range_queries_2d.md "二维区间查询"
make_stub Platinum/dc_static_range.md "分治求静态区间查询"
make_stub Platinum/sqrt_decomposition.md "分块"
make_stub Platinum/binary_jumping.md "倍增"
make_stub Platinum/small_to_large.md "启发式合并"
make_stub Platinum/hld.md "重链剖分"
make_stub Platinum/centroid_decomposition.md "点分治"
make_stub Platinum/virtual_tree.md "虚树"
make_stub Platinum/kruskal_reconstruction.md "Kruskal 重构树"
make_stub Platinum/geometry_primitives.md "几何基础"
make_stub Platinum/sweep_line.md "扫描线"
make_stub Platinum/convex_hull.md "凸包"
make_stub Platinum/convex_hull_trick.md "斜率优化"
make_stub Platinum/inclusion_exclusion.md "容斥原理"
make_stub Platinum/matrix_exponentiation.md "矩阵快速幂"
make_stub Platinum/bitsets.md "bitset"
make_stub Platinum/dc_dp.md "分治优化 DP"
make_stub Platinum/sos_dp.md "子集和 DP"
echo "done."
